name: Laravel Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, dom, fileinfo, curl
          coverage: xdebug

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit